name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: biblioteca
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run unit tests
      run: mvn test

    - name: Run integration tests
      run: mvn verify -P integration-test

    - name: Run performance tests
      run: mvn verify -P performance-test

    - name: Run load tests
      run: mvn verify -P load-test

    - name: Run security tests
      run: mvn verify -P security-test

    - name: Run mutation tests
      run: mvn verify -P mutation-test

    - name: Run coverage tests
      run: mvn verify -P coverage-test

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/surefire-reports 